- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: FACTS.LINUX.FAMILY
      ansible.builtin.shell:
        cmd: "set -o pipefail && awk -F= '$1==\"PRETTY_NAME\" { print $2 ;}' /etc/os-release | sed 's/\"//g'"
        executable: /bin/bash
      register: family
      changed_when: family.rc != 0

    - name: Debug facts
      ansible.builtin.debug:
        msg: '"distribution": "{{ family.stdout }}"'

    - name: test vault
      ansible.builtin.debug:
        msg: "{{ test_vault }}"
